spring:
  application:
    name: gateway
#指定cousul注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
    # 配置路由规则
    gateway:
      routes:
        - id: user_route
          uri: lb://users        # lb代表转发后台服务使用负载均衡,users代表服务注册中心上的服务名  注意，这里服务名称不能和路径匹配名称一致
          predicates:
            - Path=/user/**  # 路径匹配
        - id: product_route
          uri: lb://emps         # lb(load balance)代表负载均衡转发路由 注意，这里服务名称不能和路径匹配名称一致
          predicates:
            - Path=/emp/**
      discovery:
        locator:
          enabled: on     #开启根据服务名动态获取路由，不开启的话无法使用服务名对服务进行负载均衡
      #解决跨域请求问题，允许跨域访问
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
server:
  port: 8989
management:
   endpoints:
     web:
       exposure:
         include: "*"   #暴露所有web端点展示页面 http://localhost:8989/actuator/gateway/routes
#连接mq主机
spring.rabbitmq.host: 169.254.50.192
#连接mq端口
spring.rabbitmq.port: 5672
#连接mq用户名
spring.rabbitmq.username: guest
#连接mq密码
spring.rabbitmq.password: guest